export const ERR = {
  HABIT: {
    NOT_FOUND: 'ERR.HABIT.NOT_FOUND',
    STATUS_TRANSITION: 'ERR.HABIT.STATUS_TRANSITION',
    NAME_REQUIRED: 'ERR.HABIT.NAME_REQUIRED',
    TARGET_INVALID: 'ERR.HABIT.TARGET_INVALID',
    DAYS_REQUIRED: 'ERR.HABIT.DAYS_REQUIRED',
  },
  CHECKIN: {
    FUTURE_DATE: 'ERR.CHECKIN.FUTURE_DATE',
    COUNT_EXCEEDS_TARGET: 'ERR.CHECKIN.COUNT_EXCEEDS_TARGET',
    NOT_SCHEDULED: 'ERR.CHECKIN.NOT_SCHEDULED',
  },
  GOAL: {
    ACTIVE_EXISTS: 'ERR.GOAL.ACTIVE_EXISTS',
    TARGET_INVALID: 'ERR.GOAL.TARGET_INVALID',
    NOT_FOUND: 'ERR.GOAL.NOT_FOUND',
  },
  STORAGE: {
    FULL: 'ERR.STORAGE.FULL',
  },
} as const
