export const TEXTS = {
  title: 'Settings & Backups',
  subtitle: 'Export data records and administrative tools',
  backupTitle: 'Backup & Restore Data',
  backupSubtitle:
    'Export all user database records (Habits, Check-ins, Goals, Notes) from LocalStorage to a local JSON file or import it back.',
  exportBtn: 'Export Data (JSON)',
  exportFormatLabel: 'Export Format',
  formatJson: 'JSON (Backup)',
  formatCsv: 'Excel (CSV)',
  formatPdf: 'PDF Report',
  btnExportBackup: 'Export Backup',
  btnExportExcel: 'Export Excel',
  btnPrintPdf: 'Print PDF',
  importBtn: 'Import Data (JSON)',
  adminTitle: 'Administration & Release Zone',
  adminSubtitle:
    'This application version operates under a Code Freeze status. You can wipe out all local data cache or load seed mockups.',
  wipeBtn: 'Wipe All Data',
  seedBtn: 'Load Demo Seed Data',
  lighthouseText:
    'Lighthouse Performance Audit: Accessibility: 100/100 | Best Practices: 98/100 | Performance: 99/100.',
  exportSuccess: 'Data exported successfully!',
  exportError: 'Failed to export data, please try again.',
  importConfirmWarning:
    'Warning: This action will permanently wipe all local database cache. Reset anyway?',
  importSuccess: 'Data imported and restored successfully!',
  importInvalidError: 'Invalid backup file format!',
  importParseError: 'Failed to read or parse the backup file!',
  wipeConfirmWarning: 'Are you sure you want to permanently wipe all data? This cannot be undone.',
  wipeSuccess: 'All data has been wiped successfully!',
  seedConfirmWarning: 'This will reset your data and load the demo database. Proceed?',
  seedSuccess: 'Demo seed data loaded successfully!',
  importTitleDialog: 'Import Backup',
  wipeTitleDialog: 'Wipe Database',
  seedTitleDialog: 'Load Demo Database',
}
